version: '3.8'

services:
  # PostgreSQL Database (same as production)
  postgres:
    image: postgres:15-alpine
    container_name: user-docs-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-user_docs_dev}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # NestJS Application (Development)
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: user-docs-app-dev
    restart: unless-stopped
    environment:
      # Database Configuration
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${DB_NAME:-user_docs_dev}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-postgres}
      
      # JWT Configuration
      JWT_SECRET: ${JWT_SECRET:-dev-jwt-secret}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN:-24h}
      
      # Application Configuration
      NODE_ENV: development
      PORT: 3000
      
      # File Upload Configuration
      UPLOAD_DEST: ./uploads
      MAX_FILE_SIZE: ${MAX_FILE_SIZE:-10485760}
    ports:
      - "${PORT:-3001}:3000"
      - "9229:9229" # Debug port
    volumes:
      - .:/app
      - /app/node_modules
      - uploads_dev_data:/app/uploads
    networks:
      - app-network
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run start:dev

  # Redis (Development)
  redis:
    image: redis:7-alpine
    container_name: user-docs-redis-dev
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6380}:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  postgres_dev_data:
    driver: local
  uploads_dev_data:
    driver: local
  redis_dev_data:
    driver: local

networks:
  app-network:
    driver: bridge 